inputs:
  - name: reference
    metadata: https://data.nextstrain.org/files/ncov/open/reference/metadata.tsv.xz
    sequences: https://data.nextstrain.org/files/ncov/open/reference/sequences.fasta.xz

# GenBank data includes "Wuhan-Hu-1/2019" which we use as the root for this build.
refine:
  root: "Wuhan-Hu-1/2019"

escape_fraction_models:
  rbd-wuhan-hu:
    wt_seq: "Wuhan-Hu-1/2019" 
    mut_effects_df: "my_profiles/escape-frac-data/rbd_mini_binder.csv"

builds:
  ncov_reference-ef-03-23-23-t1:
    title: "Build with custom data and example data"
    # TODO: link to configuration guide
    subsampling_scheme: all
