inputs:
  - name: reference
    metadata: https://data.nextstrain.org/files/ncov/open/reference/metadata.tsv.xz
    sequences: https://data.nextstrain.org/files/ncov/open/reference/sequences.fasta.xz
  - name: custom
    metadata: my_profiles/custom_metadata.tsv
    sequences: my_profiles/custom_sequences.fasta

# GenBank data includes "Wuhan-Hu-1/2019" which we use as the root for this build.
refine:
  root: "Wuhan-Hu-1/2019"

escape_models:
  LyCoV1404-BA1:
    dms_wt_seq_id: "ON641975.1" 
    #mut_effects_df: "my_profiles/escape-frac-data/Starr_LY-CoV1404_BA1_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Starr_LY-CoV1404_BA1_raw_data_LY-CoV1404-BA1.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "LY-CoV1404 - BA1"
  268C.3-BA1:
    dms_wt_seq_id: "ON641975.1"
    #mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA1_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA1_raw_data_268C.3-BA1.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "268C.3 - BA1"
  268C.3-BA2:
    dms_wt_seq_id: "ON395492.1"
    # mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data_268C.3-BA2.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "268C.3 - BA2"
  268C.61-BA2:
    dms_wt_seq_id: "ON395492.1"
    # mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data_268C.61-BA2.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "268C.61 - BA2"
  268C.121-BA2:
    dms_wt_seq_id: "ON395492.1"
    # mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data_268C.121-BA2.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "268C.121 - BA2"
  268C.17-BA2:
    dms_wt_seq_id: "ON395492.1"
    # mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data_268C.17-BA2.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "268C.17 - BA2"
  268C.170-BA2:
    dms_wt_seq_id: "ON395492.1"
    # mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data_268C.170-BA2.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "268C.170 - BA2"
  268C.183-BA2:
    dms_wt_seq_id: "ON395492.1"
    # mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data_268C.183-BA2.csv"
    #mut_effects_df: "my_profiles/escape-frac-data/"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "268C.183 - BA2"
  268C.185-BA2:
    dms_wt_seq_id: "ON395492.1"
    # mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_all_mAbs_BA2_raw_data_268C.185-BA2.csv"
    #mut_effects_df: "my_profiles/escape-frac-data/"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "268C.185 - BA2"
  LCB1_v2.2_sensitive-WH1:
    dms_wt_seq_id: "Wuhan-Hu-1/2019" 
    # mut_effects_df: "my_profiles/escape-frac-data/Hunt_IPD_ligands_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Hunt_IPD_ligands_raw_data_LCB1_v2.2sensitive.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "LCB1_v2.2 sensitive"
  LCB1_v2.2_stringent-WH1:
    dms_wt_seq_id: "Wuhan-Hu-1/2019"
    # mut_effects_df: "my_profiles/escape-frac-data/Hunt_IPD_ligands_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Hunt_IPD_ligands_raw_data_LCB1_v2.2stringent.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "LCB1_v2.2 stringent"
  AHB2_sensitive-WH1:
    dms_wt_seq_id: "Wuhan-Hu-1/2019"
    # mut_effects_df: "my_profiles/escape-frac-data/Hunt_IPD_ligands_raw_data.csv"
    mut_effects_df: "my_profiles/escape-frac-data/Hunt_IPD_ligands_raw_data_AHB2sensitive.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"
    #site_col: "site"
    #condition: "AHB2 sensitive"

polyclonal_serum_models:
  CC67.105:
    dms_wt_seq_id: "ON641975.1"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/CC67.105/mut_escape_df.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/CC67.105/activity_wt_df.csv"
    concentrations: "210.0,10.0"
    icxx: 0.9
  CC9.104:
    dms_wt_seq_id: "ON641975.1"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/CC9.104/mut_escape_df.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/CC9.104/activity_wt_df.csv"
    concentrations: "272.0"
    icxx: 0.9
  LyCoV-1404:
    dms_wt_seq_id: "ON641975.1"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/LyCoV-1404/mut_escape_df.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/LyCoV-1404/activity_wt_df.csv"
    concentrations: "2.6"
    icxx: 0.9
  NTD_5-7:
    dms_wt_seq_id: "ON641975.1"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/NTD_5-7/mut_escape_df.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/NTD_5-7/activity_wt_df.csv"
    concentrations: "150.0"
    icxx: 0.9
  C68.59:
    dms_wt_seq_id: "ON641975.1"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/C68.59/C68.59_avg.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/C68.59/activity_wt_df.csv"
    concentrations: "80.8"
    icxx: 0.9

builds:
  03-20-23-test-additive:
    title: "Build with custom data and example data"
    # TODO: link to configuration guide
    subsampling_scheme: all
