inputs:
  - name: reference
    metadata: https://data.nextstrain.org/files/ncov/open/reference/metadata.tsv.xz
    sequences: https://data.nextstrain.org/files/ncov/open/reference/sequences.fasta.xz
  - name: ON641975_1
    metadata: my_profiles/polyclonal-data/ON641975_1_meta.tsv
    sequences: my_profiles/polyclonal-data/ON641975_1.fasta

# GenBank data includes "Wuhan-Hu-1/2019" which we use as the root for this build.
refine:
  root: "Wuhan-Hu-1/2019"

escape_fraction_models:
  rbd-wuhan-hu:
    wt_seq: "Wuhan-Hu-1/2019" 
    mut_effects_df: "my_profiles/escape-frac-data/rbd_mini_binder.csv"

polyclonal_serum_models:
  CC67.105:
    wt_seq: "ON641975.1" # must esist in the input sequences. all aamuts in prediction are relative to this
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/CC67.105/activity_wt_df.csv"
    mut_escape_df: "my_profiles/polyclonal-data/pc_escape_models/CC67.105/mut_escape_df.csv"
    concentrations: "210.0,10.0" # must be a tab-delim list .. TODO is this the best way?
  CC9.104:
    wt_seq: "ON641975.1"
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/CC9.104/activity_wt_df.csv"
    mut_escape_df: "my_profiles/polyclonal-data/pc_escape_models/CC9.104/mut_escape_df.csv"
    concentrations: "272.0"
  LyCoV-1404:
    wt_seq: "ON641975.1"
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/LyCoV-1404/activity_wt_df.csv"
    mut_escape_df: "my_profiles/polyclonal-data/pc_escape_models/LyCoV-1404/mut_escape_df.csv"
    concentrations: "2.6"
  NTD_5-7:
    wt_seq: "ON641975.1"
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/NTD_5-7/activity_wt_df.csv"
    mut_escape_df: "my_profiles/polyclonal-data/pc_escape_models/NTD_5-7/mut_escape_df.csv"
    concentrations: "150.0"

builds:
  reference-pc-ef-03-23-23-t1:
    title: "Build with custom data and example data"
    # TODO: link to configuration guide
    subsampling_scheme: all
