inputs:
  - name: global
    metadata: https://data.nextstrain.org/files/ncov/open/global/metadata.tsv.xz
    sequences: https://data.nextstrain.org/files/ncov/open/global/sequences.fasta.xz
  - name: custom
    metadata: my_profiles/custom_metadata.tsv
    sequences: my_profiles/custom_sequences.fasta

refine:
  root: "Wuhan-Hu-1/2019"

escape_models:
  LY-CoV1404-BA1_escape_score:
    dms_wt_seq_id: "ON641975.1" 
    mut_effects_df: "my_profiles/escape-frac-data/Starr_LY-CoV1404_BA1_raw_data_LY-CoV1404-BA1.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_sub"

builds:
  Starr-2022-PLoSPath:
    title: "SARS-CoV-2 phylogeny with estimated escape from LY-CoV1404 as described in Starr et al., 2022, PLoS Path."
    subsampling_scheme: all
    description: my_profiles/dmsa-pred/description.md
