inputs:
  - name: global
    metadata: https://data.nextstrain.org/files/ncov/open/global/metadata.tsv.xz
    sequences: https://data.nextstrain.org/files/ncov/open/global/sequences.fasta.xz
  - name: custom
    metadata: my_profiles/custom_metadata.tsv
    sequences: my_profiles/custom_sequences.fasta

refine:
  root: "Wuhan-Hu-1/2019"

escape_models:
  C68.3-BA2_escape_score:
    dms_wt_seq_id: "NLD/EMC-BA2-1/2022"
    mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_2023_268C.3-BA2.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_mutation"
    allow_aa_subs_at_unmeasured_sites: True
    allow_unmeasured_aa_subs_at_these_sites: "my_profiles/allow_unmeasured_aa_subs_at_these_sites_BA2_yeast_display_v2.txt"
    min_pred_pheno: 0
    max_pred_pheno: 1
  C68.61-BA2_escape_score:
    dms_wt_seq_id: "NLD/EMC-BA2-1/2022"
    mut_effects_df: "my_profiles/escape-frac-data/Guenthoer_2023_268C.61-BA2.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_mutation"
    allow_aa_subs_at_unmeasured_sites: True
    allow_unmeasured_aa_subs_at_these_sites: "my_profiles/allow_unmeasured_aa_subs_at_these_sites_BA2_yeast_display.txt"
    min_pred_pheno: 0
    max_pred_pheno: 1
  # LCB1_v2.2_sensitive-WH1_escape_score:
  #   dms_wt_seq_id: "Wuhan-Hu-1/2019" 
  #   mut_effects_df: "my_profiles/escape-frac-data/Hunt_2022_LCB1_v2.2sensitive.csv"
  #   mut_effect_col: "mut_escape"
  #   mutation_col: "aa_mutation"
  LCB1_v2.2_stringent-WH1_escape_score:
    dms_wt_seq_id: "Wuhan-Hu-1/2019"
    mut_effects_df: "my_profiles/escape-frac-data/Hunt_2022_LCB1_v2.2stringent.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_mutation"
    allow_aa_subs_at_unmeasured_sites: True
    allow_unmeasured_aa_subs_at_these_sites: "my_profiles/allow_unmeasured_aa_subs_at_these_sites_WH1_yeast_display_v2.txt"
    min_pred_pheno: 0
    max_pred_pheno: 1    
  # AHB2_sensitive-WH1_escape_score:
  #   dms_wt_seq_id: "Wuhan-Hu-1/2019"
  #   mut_effects_df: "my_profiles/escape-frac-data/Hunt_2022_AHB2sensitive.csv"
  #   mut_effect_col: "mut_escape"
  #   mutation_col: "aa_mutation"
  BD55-5514_escape_score:
    dms_wt_seq_id: "BGD/icddrb-TND-04-1538/2022"
    mut_effects_df: "my_profiles/escape-frac-data/Cao_2023_BD55-5514_raw_data.csv"
    mut_effect_col: "mut_escape"
    mutation_col: "aa_mutation"
    allow_aa_subs_at_unmeasured_sites: True
    allow_unmeasured_aa_subs_at_these_sites: "my_profiles/allow_unmeasured_aa_subs_at_these_sites_BA5_yeast_display.txt"
    min_pred_pheno: 0
    max_pred_pheno: 1
  C68.59_pc_escape_score:
    dms_wt_seq_id: "HongKong/HKU-211129-001/2021"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/C68.59/C68.59_avg.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    allow_aa_subs_at_unmeasured_sites: False
    allow_unmeasured_aa_subs_at_these_sites: "my_profiles/polyclonal-data/pc_escape_models/C68.59/allow_unmeasured_aa_subs_at_these_sites.txt"
    min_pred_pheno: 0
    max_pred_pheno: 5
  12-19_pc_escape_score:
    dms_wt_seq_id: "HongKong/HKU-211129-001/2021"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/12-19/mAb_12-19_avg.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    allow_aa_subs_at_unmeasured_sites: False
    allow_unmeasured_aa_subs_at_these_sites: "my_profiles/polyclonal-data/pc_escape_models/12-19/allow_unmeasured_aa_subs_at_these_sites.txt"
    min_pred_pheno: 0
    max_pred_pheno: 5

polyclonal_serum_models:
  CC67.105:
    dms_wt_seq_id: "HongKong/HKU-211129-001/2021"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/CC67.105/mut_escape_df.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    allow_aa_subs_at_unmeasured_sites: False
    allow_unmeasured_aa_subs_at_these_sites: "None"
    min_pred_pheno: -100
    max_pred_pheno: 100
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/CC67.105/activity_wt_df.csv"
    # concentrations: "210.0,10.0"
    icxx: 0.9
  CC9.104:
    dms_wt_seq_id: "HongKong/HKU-211129-001/2021"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/CC9.104/mut_escape_df.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    allow_aa_subs_at_unmeasured_sites: False
    allow_unmeasured_aa_subs_at_these_sites: "None"
    min_pred_pheno: -100
    max_pred_pheno: 100
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/CC9.104/activity_wt_df.csv"
    # concentrations: "272.0"
    icxx: 0.9
  NTD_5-7:
    dms_wt_seq_id: "HongKong/HKU-211129-001/2021"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/NTD_5-7/mut_escape_df.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    allow_aa_subs_at_unmeasured_sites: False
    allow_unmeasured_aa_subs_at_these_sites: "None"
    min_pred_pheno: -100
    max_pred_pheno: 100
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/NTD_5-7/activity_wt_df.csv"
    # concentrations: "150.0"
    icxx: 0.9
  C68.59:
    dms_wt_seq_id: "HongKong/HKU-211129-001/2021"
    mut_effects_df: "my_profiles/polyclonal-data/pc_escape_models/C68.59/C68.59_avg.csv"
    mut_effect_col: "escape_median"
    mutation_col: "mutation"
    allow_aa_subs_at_unmeasured_sites: False
    allow_unmeasured_aa_subs_at_these_sites: "my_profiles/polyclonal-data/pc_escape_models/C68.59/allow_unmeasured_aa_subs_at_these_sites.txt"
    min_pred_pheno: -100
    max_pred_pheno: 100
    activity_wt_df: "my_profiles/polyclonal-data/pc_escape_models/C68.59/activity_wt_df.csv"
    # concentrations: "80.8"
    icxx: 0.9

builds:
  unescaped-antibodies:
    title: "SARS-CoV-2 phylogeny with estimated escape from monoclonal antibodies with appreciable activity."
    subsampling_scheme: all
    #description: my_profiles/dmsa-pred/description.md
